### ISSUE TITLE
Serial port info is lost on page refresh

### ISSUE THREAD

**Issue by gregoryjjb** [gregoryjjb/vicini-web#4]
Two possible fixes:
* Reconstruct open ports at load time based on hardwares marked as 'open' (will not preserve contents of serial monitors)
* Store the serial state in the cookies at all times (not great but will preserve contents as well)

**Comment by JeremySorensen** [comment]
I have been thinking of this to and it comes down to accommodating commands
that are only for humans in the serial terminal, the GUI should never call
help, the sketch may have other such commands as well (the DC934A needs
such a function)
So, functions can reply with more than one line, but those functions can't
be called from the GUI

**Comment by gregoryjjb** [comment]
Fixed and cleaned by d1515c18dcb8bca64665b5ee7ed68baa9a0b7e3b
